<?php

return [
    'seo' => [
        'default_description' => 'Piramidasoft menyediakan solusi IT untuk e-procurement, business system, e-government, smart city, dan konsultasi teknologi informasi.',
        'default_og_image' => 'assets/images/hero-pages.png',
    ],

    'company' => [
        'name' => 'Piramida Teknologi Informasi',
        'short_name' => 'Piramidasoft',
        'description' => 'Penyedia solusi IT yang membantu organisasi membangun sistem digital yang relevan, stabil, dan mudah dioperasikan.',
        'address' => 'Jl. Gayung Kebonsari Timur 29, Ketintang, Kec. Gayungan, Surabaya, Indonesia',
        'primary_email' => 'marketing@piramidati.com',
        'secondary_email' => 'pti@piramidati.com',
        'phone' => '031 - 5828 3512',
        'whatsapp' => '085954320729',
        'linkedin' => 'Piramida Teknologi Informasi',
        'language' => 'Indonesia',
        'business_hours' => [
            'weekday' => 'Hari kerja - Buka',
            'weekend' => 'Akhir pekan - Tutup',
            'time' => '8 AM - 9 PM',
        ],
    ],

    'hero_slides' => [
        [
            'tag' => 'Tentang kami',
            'title' => 'Business Intelligence',
            'subtitle' => 'Visualisasi infografis untuk presentasi yang menarik dan memudahkan pengguna, analis, serta manajemen dalam memahami data terkini.',
            'image' => 'assets/images/hero.png',
            'primary' => ['text' => 'Baca selengkapnya', 'route' => 'about'],
            'secondary' => ['text' => 'Hubungi kami', 'route' => 'contact'],
        ],
        [
            'tag' => 'Tentang kami',
            'title' => 'Dapatkan Solusi Lebih Baik untuk Bisnis Anda',
            'subtitle' => 'Kami membantu mewujudkan ide kreatif perusahaan menjadi solusi digital yang siap dipakai dan mudah dikembangkan.',
            'image' => 'assets/images/hero.png',
            'primary' => ['text' => 'Baca selengkapnya', 'route' => 'about'],
            'secondary' => ['text' => 'Hubungi kami', 'route' => 'contact'],
        ],
        [
            'tag' => 'Tentang kami',
            'title' => 'Data Warehouse',
            'subtitle' => 'Gudang data terintegrasi untuk input, verifikasi, monitoring, dan integrasi data lintas aplikasi operasional maupun dokumen.',
            'image' => 'assets/images/hero.png',
            'primary' => ['text' => 'Baca selengkapnya', 'route' => 'about'],
            'secondary' => ['text' => 'Hubungi kami', 'route' => 'contact'],
        ],
        [
            'tag' => 'Tentang kami',
            'title' => 'Membantu Organisasi Berinovasi',
            'subtitle' => 'Kami membantu klien menyelesaikan tantangan hari ini dan mengantisipasi kebutuhan masa depan lewat implementasi sistem yang efektif.',
            'image' => 'assets/images/hero.png',
            'primary' => ['text' => 'Baca selengkapnya', 'route' => 'about'],
            'secondary' => ['text' => 'Hubungi kami', 'route' => 'contact'],
        ],
        [
            'tag' => 'Tentang kami',
            'title' => 'Penyedia Solusi IT',
            'subtitle' => 'Didukung pengalaman melayani ratusan pelanggan di Indonesia untuk pengembangan aplikasi, konsultasi sistem, dan transformasi digital.',
            'image' => 'assets/images/hero.png',
            'primary' => ['text' => 'Baca selengkapnya', 'route' => 'about'],
            'secondary' => ['text' => 'Hubungi kami', 'route' => 'contact'],
        ],
    ],

    'home' => [
        'services' => [
            [
                'title' => 'E-PROCUREMENT',
                'description' => 'Aplikasi untuk pengelolaan manajemen dan administrasi pengadaan barang atau jasa secara elektronik di perusahaan.',
                'image' => 'assets/images/E-Procurement.png',
                'icon' => 'PC',
            ],
            [
                'title' => 'ERP BUSINESS SYSTEM',
                'description' => 'Aplikasi untuk membantu perusahaan mengelola keuangan, gudang, inventaris, pembelian, penjualan, dan manufaktur.',
                'image' => 'assets/images/erp-business-system.png',
                'icon' => 'BS',
            ],
            [
                'title' => 'IT CONSULTANT',
                'description' => 'Solusi terintegrasi lengkap untuk konsultasi, perancangan, penerapan, dan pemeliharaan produk teknologi perusahaan.',
                'image' => 'assets/images/it-consultant.png',
                'icon' => 'IT',
            ],
            [
                'title' => 'E-GOVERNMENT & SMART CITY',
                'description' => 'Penerapan teknologi informasi untuk memperkuat hubungan pemerintah dengan masyarakat dan pemangku kepentingan lainnya.',
                'image' => 'assets/images/e-government.png',
                'icon' => 'EG',
            ],
        ],
        'featured_products' => [
            [
                'tab' => 'Tendering',
                'tab_mobile' => 'Tendering',
                'title' => 'TENDERING',
                'image' => 'assets/images/E-Procurement.png',
                'summary' => [
                    'Modul untuk menjalankan proses pengadaan dengan tender maupun penunjukan langsung. Paket pekerjaan berasal dari modul procurement planning.',
                    'Proses meliputi persiapan tender, pengumuman, aanwijzing, pemasukan penawaran, pembukaan dan evaluasi hingga penetapan pemenang.',
                    'Dilengkapi sistem penyandian dokumen penawaran untuk menjaga keamanan informasi.',
                ],
                'link' => null,
            ],
            [
                'tab' => 'HRIS/HRMS',
                'tab_mobile' => 'HRIS/HRMS',
                'title' => 'HRIS / HRMS',
                'image' => 'assets/images/latar-belakang-divisi.png',
                'summary' => [
                    'Sistem manajemen SDM terintegrasi untuk personalia, absensi, cuti, payroll, hingga evaluasi kinerja.',
                    'Mempermudah workflow HR berbasis data dan menyiapkan laporan operasional secara real-time.',
                ],
                'link' => null,
            ],
            [
                'tab' => 'Procurement Planning',
                'tab_mobile' => "Procurement\nPlanning",
                'title' => 'PROCUREMENT PLANNING',
                'image' => 'assets/images/E-Procurement.png',
                'summary' => [
                    'Modul perencanaan kebutuhan pengadaan untuk menyusun paket pekerjaan, anggaran, serta target waktu pelaksanaan.',
                    'Seluruh data perencanaan menjadi sumber utama sebelum proses tender maupun pembelian langsung dijalankan.',
                ],
                'link' => null,
            ],
            [
                'tab' => 'eGovernment',
                'tab_mobile' => 'eGovernment',
                'title' => 'E-GOVERNMENT',
                'image' => 'assets/images/e-government.png',
                'summary' => [
                    'Solusi digital pemerintahan untuk mempercepat pelayanan publik dan meningkatkan transparansi pengelolaan data.',
                    'Mencakup layanan perizinan, pengaduan, dashboard kinerja, hingga integrasi lintas perangkat daerah.',
                ],
                'link' => null,
            ],
            [
                'tab' => 'Insight Gov',
                'tab_mobile' => 'Insight Gov',
                'title' => 'INSIGHT GOV',
                'image' => 'assets/images/e-government.png',
                'summary' => [
                    'Dashboard analitik pemerintahan untuk membantu pimpinan memantau KPI, tren pelayanan, dan performa organisasi.',
                    'Visualisasi data disusun agar mudah dipahami untuk mendukung pengambilan keputusan yang cepat dan tepat.',
                ],
                'link' => null,
            ],
        ],
        'clients' => [
            ['name' => 'Airnav', 'logo' => 'assets/logo/client/airnav.png'],
            ['name' => 'Bank Kalbar', 'logo' => 'assets/logo/client/bank-kalbar.png'],
            ['name' => 'Bank Sumsel', 'logo' => 'assets/logo/client/bank-sumsel.png'],
            ['name' => 'BPWS', 'logo' => 'assets/logo/client/bpws.png'],
            ['name' => 'BSG', 'logo' => 'assets/logo/client/bsg.png'],
            ['name' => 'CMS', 'logo' => 'assets/logo/client/cms.png'],
            ['name' => 'INKA', 'logo' => 'assets/logo/client/inka.png'],
            ['name' => 'Jer Basuki', 'logo' => 'assets/logo/client/jer-basuki.png'],
            ['name' => 'JICA', 'logo' => 'assets/logo/client/jica.png'],
            ['name' => 'Kab. Malang', 'logo' => 'assets/logo/client/kab-malang.png'],
            ['name' => 'Kab. Nunukan', 'logo' => 'assets/logo/client/kab-nunukan.png'],
            ['name' => 'Kab. Probolinggo', 'logo' => 'assets/logo/client/kab-probolinggo.png'],
            ['name' => 'Kab. Sidoarjo', 'logo' => 'assets/logo/client/kab-sidoarjo.png'],
            ['name' => 'Kotamadya', 'logo' => 'assets/logo/client/kotamadya.png'],
            ['name' => 'Lamongan', 'logo' => 'assets/logo/client/lamongan.png'],
            ['name' => 'Madu Ganda', 'logo' => 'assets/logo/client/madu-ganda.png'],
            ['name' => 'Magetan', 'logo' => 'assets/logo/client/magetan.png'],
            ['name' => 'Manakarra', 'logo' => 'assets/logo/client/manakarra.png'],
            ['name' => 'Nganjuk', 'logo' => 'assets/logo/client/nganjuk.png'],
            ['name' => 'Ngawi', 'logo' => 'assets/logo/client/ngawi.png'],
            ['name' => 'PINS', 'logo' => 'assets/logo/client/pins.png'],
            ['name' => 'PJB', 'logo' => 'assets/logo/client/pjb.png'],
            ['name' => 'POMI', 'logo' => 'assets/logo/client/pomi.png'],
            ['name' => 'PTPN', 'logo' => 'assets/logo/client/ptpn.png'],
            ['name' => 'Sugih Mukti', 'logo' => 'assets/logo/client/sugih-mukti.png'],
            ['name' => 'Sumekar', 'logo' => 'assets/logo/client/sumekar.png'],
            ['name' => 'Trunojoyo', 'logo' => 'assets/logo/client/trunojoyo.png'],
            ['name' => 'Wijna', 'logo' => 'assets/logo/client/wijna.png'],
        ],
    ],

    'products' => [
        'categories' => [
            ['label' => 'Business System', 'key' => 'business-system'],
            ['label' => 'E-Procurement', 'key' => 'e-procurement'],
            ['label' => 'E-Government & Smart City', 'key' => 'e-government-smart-city'],
            ['label' => 'IT Consultant', 'key' => 'it-consultant'],
        ],
        'items' => [
            [
                'name' => 'HRIS/HRMS',
                'description' => 'Aplikasi perusahaan untuk mengelola informasi sumber daya manusia perusahaan.',
                'image' => 'assets/images/latar-belakang-divisi.png',
                'category' => 'Business System',
                'category_key' => 'business-system',
                'url' => null,
            ],
            [
                'name' => 'Presensi / Time Attendance',
                'description' => 'Aplikasi presensi yang mudah, cepat, dan akurat untuk berbagai perusahaan maupun instansi pemerintah.',
                'image' => 'assets/images/E-Procurement.png',
                'category' => 'Business System',
                'category_key' => 'business-system',
                'url' => null,
            ],
            [
                'name' => 'Virtual Tour',
                'description' => 'Aplikasi interaktif berbasis 360 derajat untuk simulasi lokasi secara nyata tanpa kunjungan langsung.',
                'image' => 'assets/images/hero-pages.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
            [
                'name' => 'Aplikasi Potensi dan Peluang Investasi',
                'description' => 'Aplikasi informasi potensi dan peluang investasi yang menyajikan prospektus lengkap serta terbaru.',
                'image' => 'assets/images/e-government.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
            [
                'name' => 'Aplikasi Pengadaan Unit Pelayanan',
                'description' => 'Aplikasi pengadaan yang mempermudah proses lelang dan administrasi barang maupun jasa secara efisien.',
                'image' => 'assets/images/it-support.png',
                'category' => 'E-Procurement',
                'category_key' => 'e-procurement',
                'url' => null,
            ],
            [
                'name' => 'Contractor Safety Management System (CSMS)',
                'description' => 'Aplikasi pengelolaan keselamatan kerja kontraktor untuk memastikan kepatuhan terhadap standar K3 perusahaan.',
                'image' => 'assets/images/erp-business-system.png',
                'category' => 'Business System',
                'category_key' => 'business-system',
                'url' => null,
            ],
            [
                'name' => 'Rusunawa - Billing',
                'description' => 'Aplikasi pengelolaan penghuni dan penagihan sewa rusunawa yang terintegrasi untuk administrasi dan pelaporan.',
                'image' => 'assets/images/about-me.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
            [
                'name' => 'Aplikasi Geographical Information System (APGIS)',
                'description' => 'Sistem informasi geografis untuk mengelola dan menyajikan data spasial secara terintegrasi.',
                'image' => 'assets/images/e-government.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
            [
                'name' => 'Business Intelligence (BI)',
                'description' => 'Aplikasi pengolahan dan penyajian data terintegrasi untuk monitoring kinerja dan pengambilan keputusan.',
                'image' => 'assets/images/pti.png',
                'category' => 'Business System',
                'category_key' => 'business-system',
                'url' => null,
            ],
            [
                'name' => 'Data Management and Dashboard (e-Government)',
                'description' => 'Aplikasi pengelolaan dan integrasi data terstruktur dengan dashboard visual untuk monitoring dan pelaporan.',
                'image' => 'assets/images/e-government.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
            [
                'name' => 'Tendering',
                'description' => 'Aplikasi pengelolaan proses pengadaan melalui tender maupun penunjukan langsung yang aman dan terdokumentasi.',
                'image' => 'assets/images/E-Procurement.png',
                'category' => 'E-Procurement',
                'category_key' => 'e-procurement',
                'url' => null,
            ],
            [
                'name' => 'Purchasing',
                'description' => 'Aplikasi pengelolaan pembelian melalui katalog produk yang terintegrasi dari pemesanan hingga draft purchase order.',
                'image' => 'assets/images/E-Procurement.png',
                'category' => 'E-Procurement',
                'category_key' => 'e-procurement',
                'url' => null,
            ],
            [
                'name' => 'Procurement Planning',
                'description' => 'Aplikasi perencanaan pengadaan untuk pengelolaan paket pekerjaan, anggaran, jadwal, dan persetujuan.',
                'image' => 'assets/images/E-Procurement.png',
                'category' => 'E-Procurement',
                'category_key' => 'e-procurement',
                'url' => null,
            ],
            [
                'name' => 'PostgreSQL Premium Maintenance Support',
                'description' => 'Layanan pemeliharaan dan dukungan PostgreSQL yang mencakup instalasi, keamanan, backup, dan pemulihan.',
                'image' => 'assets/images/it-consultant.png',
                'category' => 'IT Consultant',
                'category_key' => 'it-consultant',
                'url' => null,
            ],
            [
                'name' => 'Insight GOV',
                'description' => 'Aplikasi pengelolaan data terintegrasi yang menggabungkan data warehouse, business intelligence, dan open data.',
                'image' => 'assets/images/e-government.png',
                'category' => 'E-Government & Smart City',
                'category_key' => 'e-government-smart-city',
                'url' => null,
            ],
        ],
    ],

    'publications' => [
        'items' => [
            [
                'img' => 'assets/images/pub-egov.png',
                'title' => 'Product Profile',
                'subtitle' => 'E-Government Service Software',
                'desc' => 'Berikut adalah product profile E-Government service software PT Piramida Teknologi Informasi.',
                'pdf' => 'assets/pdf/e-government-service-software.pdf',
                'type' => 'product',
            ],
            [
                'img' => 'assets/images/pub-soft.png',
                'title' => 'Product Profile',
                'subtitle' => 'Software Solution',
                'desc' => 'Berikut adalah product profile software solution PT Piramida Teknologi Informasi.',
                'pdf' => 'assets/pdf/software-solution.pdf',
                'type' => 'product',
            ],
            [
                'img' => 'assets/images/pub-company.png',
                'title' => 'Company Profile',
                'subtitle' => 'Booklet Piramida Teknologi Indonesia',
                'desc' => 'Berikut adalah dokumen company profile PT Piramida Teknologi Informasi.',
                'pdf' => 'assets/pdf/company-profile.pdf',
                'type' => 'download',
            ],
            [
                'img' => 'assets/images/pub-brosur.png',
                'title' => 'Brosur Insight GOV',
                'subtitle' => null,
                'desc' => 'Silakan unduh brosur berikut untuk mengetahui informasi Insight GOV lebih detail.',
                'pdf' => 'assets/pdf/brosur.pdf',
                'type' => 'download',
            ],
        ],
    ],

    'internships' => [
        'divisions' => [
            [
                'title' => 'Web Development',
                'desc' => 'Siswa magang belajar membangun dan mengelola website secara langsung sesuai standar industri.',
                'img' => 'Web Development.png',
            ],
            [
                'title' => 'Mobile Development',
                'desc' => 'Siswa magang belajar mengembangkan aplikasi mobile yang fungsional dan siap digunakan.',
                'img' => 'Mobile Development.png',
            ],
            [
                'title' => 'UI/UX Designer',
                'desc' => 'Siswa magang belajar merancang tampilan dan pengalaman pengguna yang intuitif serta menarik.',
                'img' => 'UI_UX Designer.png',
            ],
            [
                'title' => 'IT Support',
                'desc' => 'Siswa magang belajar menangani instalasi, troubleshooting, dan pemeliharaan sistem IT.',
                'img' => 'IT Support.png',
            ],
        ],
        'benefits' => [
            'Terlibat dalam real proyek' => 'Berkesempatan bekerja langsung pada proyek nyata yang berdampak.',
            'Lingkungan kerja yang profesional' => 'Suasana kerja yang mendukung pengembangan dan pertumbuhan kemampuan Anda.',
            'Mentor berpengalaman' => 'Bimbingan langsung dari profesional yang ahli di bidangnya.',
            'Sertifikat magang' => 'Sertifikat resmi sebagai bukti pengalaman magang Anda.',
        ],
    ],

    'careers' => [
        'vacancies' => [
            [
                'slug' => 'fullstack-developer',
                'title' => 'Fullstack Developer',
                'employment_type' => 'Full Time',
                'summary' => 'Dibutuhkan Fullstack Developer untuk bergabung dengan tim kami.',
                'headline' => 'We Are Hiring Fullstack Developer - Full Time',
                'description' => 'Kami mencari Fullstack Developer yang tidak hanya mampu membangun sistem yang stabil dan scalable, tetapi juga memahami kebutuhan bisnis serta mampu menerjemahkannya menjadi solusi digital yang efisien, terintegrasi, dan berdampak nyata bagi pengguna.',
                'qualifications' => [
                    'Minimal D3/S1 Teknik Informatika, Sistem Informasi, Ilmu Komputer, atau jurusan relevan.',
                    'Minimal 3-5 tahun pengalaman sebagai Fullstack Developer.',
                    'Wajib melampirkan portofolio website, aplikasi, sistem backend/API, atau project GitHub.',
                ],
                'skills' => [
                    'Mahir menggunakan teknologi frontend dan backend modern seperti JavaScript/TypeScript, React/Vue/Next.js, Node.js, Laravel, atau sejenisnya.',
                    'Mampu membangun RESTful API, mengelola database seperti MySQL/PostgreSQL/MongoDB, serta mengintegrasikan layanan pihak ketiga.',
                    'Memahami arsitektur aplikasi, clean code, dan best practice pengembangan software.',
                    'Terbiasa menggunakan Git dan workflow kolaboratif seperti GitHub atau GitLab.',
                    'Memahami konsep responsive web dan mampu mengimplementasikan UI yang optimal di berbagai device.',
                    'Terbiasa bekerja dalam tim lintas divisi dengan dokumentasi dan struktur kode yang rapi.',
                    'Memahami dasar DevOps seperti deployment, CI/CD, dan server management menjadi nilai tambah.',
                ],
                'salary_range' => 'Rp10.000.000 - Rp15.000.000',
                'salary_note' => '(disesuaikan dengan pengalaman dan skill)',
                'salary_context' => 'Jika kandidat memiliki pengalaman lebih dari 5 tahun dengan portofolio kompleks, range dapat disesuaikan.',
                'benefits' => [
                    'Lingkungan kerja kreatif dan suportif.',
                    'Terlibat dalam project skala pemerintahan dan enterprise.',
                    'Kesempatan pengembangan karier dan skill improvement.',
                    'Bonus performa berdasarkan evaluasi kinerja.',
                ],
                'poster' => 'assets/images/poster-lowongan.png',
            ],
        ],
    ],
];
